module.exports = {
  tableName: 'events',
  columns: {
    id: 'id',
    artistId: 'artist_id',
    title: 'title',
    slug: 'slug',
    description: 'description',
    venueName: 'venue_name',
    venueAddress: 'venue_address',
    city: 'city',
    country: 'country',
    lat: 'lat',
    lng: 'lng',
    startDatetime: 'start_datetime',
    endDatetime: 'end_datetime',
    timezone: 'timezone',
    bannerUrl: 'banner_url',
    status: 'status',
    isFree: 'is_free',
    capacity: 'capacity',
    deletedAt: 'deleted_at',
  },
};
